name: blog
auth:
    key: enLQb0qYT9VRT6TQFrzNmfEj9ve8chVwIBU2VMI32lM=
    expires: 7200

server:
    port: 5555
    mode: debug
    readTimeout: 60
    writeTimeout: 60

upload:
    path: upload/
    image:
        path: images/
        maxSize: 5
        allowExtensions: .jpeg,.jpg,.png
log:
    path: logs/
    extension: log
    dateFormat: 20200405

database:
    driver: MySQL
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    database: blog
    prefix: gb_
    charset: utf8
    collate: utf8_general_ci

redis:
    host: 127.0.0.1
    port: 6379
    password:
    maxIdle: 30
    maxActive: 30
    idleTimeout: 200